# Numpy Assignment

## Requirements
This notebook requires the Anaconda virtual env that was created during the first week of this course and named _e4_trainor_python_course_.

This is a stand-alone notebook.

## Overview
### Basketball Game Ticket Tracking Problem
We are tracking the ticket "sales" at basketball games hosted by particular teams. 
Note that "sales" is placed in quotations here because Promotional Tickets are not so much sold as given away.

We will be creating an array of game ticket "sales" records.
Each row of the array represents a game hosted by particular team (a game record).
The columns represent the number of a particular type of ticket "sold" for that game:
Season Tickets (1st column), Regular Tickets (2nd column), Promotional Tickets (3rd column).

## Imports

In [1]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


### A 1D array indicating which team is associated with which game record

In [2]:
team_list = ['Blues',
             'Reds',
             'Greens',
             'Reds',
             'Yellows',
             'Oranges',
             'Reds',
             'Blues',
             'Yellows',
             'Reds']

team_array = np.array(team_list)
team_array

array(['Blues', 'Reds', 'Greens', 'Reds', 'Yellows', 'Oranges', 'Reds',
       'Blues', 'Yellows', 'Reds'], dtype='<U7')

### A 2D array of game records
Each row represents a game.
Each column represents the quantity of tickets "sold" of a particular type: Season Tickets, Regular Tickets, Promotional Tickets.
Two versions of the data are provided:  test and actual.
Test values can be used to evaluate code.
Actual values can be used to get proper answers.

In [3]:
game_record_list = [

    # test values
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],
    # [1, 2, 3],

    # actual values
    [24997, 10170, 1389],
    [24989, 10647, 1657],
    [24957, 9693, 1155],
    [24977, 9461, 1602],
    [24970, 7630, 1470],
    [24985, 7310, 1774],
    [24981, 8484, 1701],
    [24975, 7788, 1626],
    [24961, 7513, 1232],
    [24950, 9695, 1079],
]

game_record_array = np.array(game_record_list)
game_record_array

array([[24997, 10170,  1389],
       [24989, 10647,  1657],
       [24957,  9693,  1155],
       [24977,  9461,  1602],
       [24970,  7630,  1470],
       [24985,  7310,  1774],
       [24981,  8484,  1701],
       [24975,  7788,  1626],
       [24961,  7513,  1232],
       [24950,  9695,  1079]])

### Create a new game record array containing only game records for Reds

In [4]:
reds_game_record = game_record_array[team_array == 'Reds']
reds_game_record

array([[24989, 10647,  1657],
       [24977,  9461,  1602],
       [24981,  8484,  1701],
       [24950,  9695,  1079]])

### Calculate total tickets "sold" in each of Reds game records

In [5]:
reds_game_record.sum(axis=1)

array([37293, 36040, 35166, 35724])

### Calculate total tickets "sold" by Reds for each ticket type

In [6]:
reds_game_record.sum(axis=0)

array([99897, 38287,  6039])

### Calculate total tickets "sold" by Reds

In [7]:
reds_game_record.sum()

144223

### Calculate total Season Tickets and Regular Tickets "sold" by Reds

In [8]:
season_regular_tickets = reds_game_record[:, 0:2]
season_regular_tickets.sum()

138184

### Calculate total Regular Tickets and Promotional Tickets "sold" by Reds

In [9]:
regular_promotional_tickets = reds_game_record[:, 1:]
regular_promotional_tickets.sum()

44326

### Challenge: Create and show an array containing Reds Regular Tickets "sold" by game

In [10]:
reds_regular_tickets_by_game = reds_game_record[:, 1]
reds_regular_tickets_by_game

array([10647,  9461,  8484,  9695])

### Challenge: Calculate total Regular Tickets "sold" by Reds


In [11]:
reds_total_regular_tickets = reds_game_record[:, 1]
reds_total_regular_tickets.sum()

38287