# Numpy Tutorial

## Requirements
This notebook requires the Anaconda virtual env that was created during the first week of this course and named _e4_trainor_python_course_.

This is a stand-alone notebook.

## Overview
### Sales Tracking Problem
We are tracking sales of some products by salesperson.
We will be creating an array of sales records.
Each row of the array represents a sale by a particular sales person (a sales record).
Each column entry represents the number of units of that product included in the sale.

## Imports

In [1]:
import numpy as np

### A 1D array indicating which salesperson is associated with which sales record

In [2]:
salesperson_list = ['Susan',
                    'Bob',
                    'Susan',
                    'Amit',
                    'Cesar',
                    'Xialiang',
                    'Susan',
                    'Amit',
                    'Bob',
                    'Cesar']

salesperson_array = np.array(salesperson_list)
salesperson_array

array(['Susan', 'Bob', 'Susan', 'Amit', 'Cesar', 'Xialiang', 'Susan',
       'Amit', 'Bob', 'Cesar'], dtype='<U8')

### A 2D array of sales records
Each row represents a sale.
Each column represents the quantity of a particular product included in that sale.
Two versions of the data are provided:  test and actual.
Test values are used to evaluate code.
Actual values are used to get proper answers.

In [3]:
sales_record_list = [
    
    # test values
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],
    # [1, 2, 3, 4, 5],

    # actual values
    [344, 279, 1642, 1706, 647],
    [1817, 1803, 1282, 1990, 686],
    [2234, 365, 1473, 876, 152],
    [1321, 2347, 129, 1397, 2109],
    [2331, 93, 1403, 1736, 761],
    [2014, 985, 970, 2498, 212],
    [2488, 430, 2034, 910, 550],
    [1172, 695, 1816, 1428, 1169],
    [766, 1460, 704, 1783, 374],
    [1067, 1092, 2312, 1333, 369],
]

sales_record_array = np.array(sales_record_list)
sales_record_array

array([[ 344,  279, 1642, 1706,  647],
       [1817, 1803, 1282, 1990,  686],
       [2234,  365, 1473,  876,  152],
       [1321, 2347,  129, 1397, 2109],
       [2331,   93, 1403, 1736,  761],
       [2014,  985,  970, 2498,  212],
       [2488,  430, 2034,  910,  550],
       [1172,  695, 1816, 1428, 1169],
       [ 766, 1460,  704, 1783,  374],
       [1067, 1092, 2312, 1333,  369]])

### Create a new sales record array containing only sales records for Susan

In [4]:
susan_sales_array = sales_record_array[salesperson_array == 'Susan']
susan_sales_array

array([[ 344,  279, 1642, 1706,  647],
       [2234,  365, 1473,  876,  152],
       [2488,  430, 2034,  910,  550]])

### Calculate total units sold in each of Susan's sales records

In [5]:
susan_sales_array.sum(axis=1)

array([4618, 5100, 6412])

### Calculate total units sold by Susan for each product

In [6]:
susan_sales_array.sum(axis=0)

array([5066, 1074, 5149, 3492, 1349])

### Calculate total units sold by Susan

In [7]:
susan_sales_array.sum()

16130

### Calculate total units sold by Susan for the first and second products

In [8]:
products_one_two = susan_sales_array[:, :2]
products_one_two.sum()

6140

### Calculate units sold by Susan for the fourth and fifth products

In [9]:
products_four_five = susan_sales_array[:, 3:5]
products_four_five.sum()

4841